
   2025-05-30T11:21:48.65+0000 [APP/PROC/WEB/0] ERR /home/vcap/deps/0/python/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (0, 0, 612.0, 792.0)
   2025-05-30T11:21:48.65+0000 [APP/PROC/WEB/0] ERR cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
   2025-05-30T11:21:48.74+0000 [APP/PROC/WEB/0] ERR /home/vcap/deps/0/python/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.19, 83.0236, 545.1891360000002, 219.90502857142843)
   2025-05-30T11:21:48.74+0000 [APP/PROC/WEB/0] ERR cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
   2025-05-30T11:21:48.89+0000 [APP/PROC/WEB/0] ERR /home/vcap/deps/0/python/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (56.0, 552.1682000000001, 553.9087839999995, 791.9470566037736)
   2025-05-30T11:21:48.89+0000 [APP/PROC/WEB/0] ERR cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
   2025-05-30T11:21:48.89+0000 [APP/PROC/WEB/0] ERR /home/vcap/deps/0/python/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (63.92, 479.3282, 485.2687839999996, 600.9124766037736)
   2025-05-30T11:21:48.89+0000 [APP/PROC/WEB/0] ERR cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
   2025-05-30T11:21:48.96+0000 [APP/PROC/WEB/0] ERR /home/vcap/deps/0/python/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (56.0, 508.0082, 540.1081959999997, 727.4046299999999)
   2025-05-30T11:21:48.96+0000 [APP/PROC/WEB/0] ERR cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
   2025-05-30T11:21:49.33+0000 [APP/PROC/WEB/0] ERR /home/vcap/deps/0/python/lib/python3.10/site-packages/camelot/parsers/base.py:238: UserWarning: No tables found in table area (0, 0, 612.0, 792.0)
   2025-05-30T11:21:49.33+0000 [APP/PROC/WEB/0] ERR cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
user: EarningsAI_V7_ST $ 
